/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiAccountMeta {
    #[serde(rename = "programID", skip_serializing_if = "Option::is_none")]
    pub program_id: Option<String>,
    #[serde(rename = "isSigner", skip_serializing_if = "Option::is_none")]
    pub is_signer: Option<bool>,
    #[serde(rename = "isWritable", skip_serializing_if = "Option::is_none")]
    pub is_writable: Option<bool>,
}

impl ApiAccountMeta {
    pub fn new() -> ApiAccountMeta {
        ApiAccountMeta {
            program_id: None,
            is_signer: None,
            is_writable: None,
        }
    }
}

