/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiPostOrderResponse {
    #[serde(rename = "transaction", skip_serializing_if = "Option::is_none")]
    pub transaction: Option<Box<models::ApiTransactionMessage>>,
    #[serde(rename = "openOrdersAddress", skip_serializing_if = "Option::is_none")]
    pub open_orders_address: Option<String>,
}

impl ApiPostOrderResponse {
    pub fn new() -> ApiPostOrderResponse {
        ApiPostOrderResponse {
            transaction: None,
            open_orders_address: None,
        }
    }
}

