/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiSide {
    #[serde(rename = "S_UNKNOWN")]
    Unknown,
    #[serde(rename = "S_BID")]
    Bid,
    #[serde(rename = "S_ASK")]
    Ask,

}

impl std::fmt::Display for ApiSide {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Unknown => write!(f, "S_UNKNOWN"),
            Self::Bid => write!(f, "S_BID"),
            Self::Ask => write!(f, "S_ASK"),
        }
    }
}

impl Default for ApiSide {
    fn default() -> ApiSide {
        Self::Unknown
    }
}

