/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiDirection {
    #[serde(rename = "D_ASCENDING")]
    Ascending,
    #[serde(rename = "D_DESCENDING")]
    Descending,

}

impl std::fmt::Display for ApiDirection {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ascending => write!(f, "D_ASCENDING"),
            Self::Descending => write!(f, "D_DESCENDING"),
        }
    }
}

impl Default for ApiDirection {
    fn default() -> ApiDirection {
        Self::Ascending
    }
}

