/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiPostPumpFunSwapRequest {
    #[serde(rename = "userAddress", skip_serializing_if = "Option::is_none")]
    pub user_address: Option<String>,
    #[serde(rename = "bondingCurveAddress", skip_serializing_if = "Option::is_none")]
    pub bonding_curve_address: Option<String>,
    #[serde(rename = "tokenAddress", skip_serializing_if = "Option::is_none")]
    pub token_address: Option<String>,
    #[serde(rename = "tokenAmount", skip_serializing_if = "Option::is_none")]
    pub token_amount: Option<f64>,
    #[serde(rename = "solThreshold", skip_serializing_if = "Option::is_none")]
    pub sol_threshold: Option<f64>,
    #[serde(rename = "isBuy", skip_serializing_if = "Option::is_none")]
    pub is_buy: Option<bool>,
    /// Optional: specifies total compute limit to be allocated for all instructions within the created tx
    #[serde(rename = "computeLimit", skip_serializing_if = "Option::is_none")]
    pub compute_limit: Option<i64>,
    /// Optional: specifies compute price in microlamports to be included as a part of instruction, known as priority fee
    #[serde(rename = "computePrice", skip_serializing_if = "Option::is_none")]
    pub compute_price: Option<String>,
    /// Optional: Specifies a tip amount that will be used to pay for front-running protection and/or bundle submission services. Minimum value is 1025
    #[serde(rename = "tip", skip_serializing_if = "Option::is_none")]
    pub tip: Option<String>,
}

impl ApiPostPumpFunSwapRequest {
    pub fn new() -> ApiPostPumpFunSwapRequest {
        ApiPostPumpFunSwapRequest {
            user_address: None,
            bonding_curve_address: None,
            token_address: None,
            token_amount: None,
            sol_threshold: None,
            is_buy: None,
            compute_limit: None,
            compute_price: None,
            tip: None,
        }
    }
}

