/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiTransactionMessageHeader {
    #[serde(rename = "numRequiredSignatures", skip_serializing_if = "Option::is_none")]
    pub num_required_signatures: Option<i64>,
    #[serde(rename = "numReadonlySignedAccounts", skip_serializing_if = "Option::is_none")]
    pub num_readonly_signed_accounts: Option<i64>,
    #[serde(rename = "numReadonlyUnsignedAccounts", skip_serializing_if = "Option::is_none")]
    pub num_readonly_unsigned_accounts: Option<i64>,
}

impl ApiTransactionMessageHeader {
    pub fn new() -> ApiTransactionMessageHeader {
        ApiTransactionMessageHeader {
            num_required_signatures: None,
            num_readonly_signed_accounts: None,
            num_readonly_unsigned_accounts: None,
        }
    }
}

