/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiTransactionMetaTokenBalance {
    #[serde(rename = "accountIndex", skip_serializing_if = "Option::is_none")]
    pub account_index: Option<i64>,
    #[serde(rename = "mint", skip_serializing_if = "Option::is_none")]
    pub mint: Option<String>,
    #[serde(rename = "uiTokenAmount", skip_serializing_if = "Option::is_none")]
    pub ui_token_amount: Option<Box<models::ApiUiTokenAmount>>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
}

impl ApiTransactionMetaTokenBalance {
    pub fn new() -> ApiTransactionMetaTokenBalance {
        ApiTransactionMetaTokenBalance {
            account_index: None,
            mint: None,
            ui_token_amount: None,
            owner: None,
        }
    }
}

