/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiGetTransactionResponse {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<models::ApiTransactionMeta>>,
    #[serde(rename = "slot", skip_serializing_if = "Option::is_none")]
    pub slot: Option<String>,
    #[serde(rename = "blockTime", skip_serializing_if = "Option::is_none")]
    pub block_time: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
}

impl ApiGetTransactionResponse {
    pub fn new() -> ApiGetTransactionResponse {
        ApiGetTransactionResponse {
            status: None,
            metadata: None,
            slot: None,
            block_time: None,
            version: None,
        }
    }
}

