/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiMarketStatus {
    #[serde(rename = "MS_UNKNOWN")]
    Unknown,
    #[serde(rename = "MS_ONLINE")]
    Online,

}

impl std::fmt::Display for ApiMarketStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Unknown => write!(f, "MS_UNKNOWN"),
            Self::Online => write!(f, "MS_ONLINE"),
        }
    }
}

impl Default for ApiMarketStatus {
    fn default() -> ApiMarketStatus {
        Self::Unknown
    }
}

