/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApiOrderStatus {
    #[serde(rename = "OS_UNKNOWN")]
    Unknown,
    #[serde(rename = "OS_OPEN")]
    Open,
    #[serde(rename = "OS_PARTIAL_FILL")]
    PartialFill,
    #[serde(rename = "OS_CANCELLED")]
    Cancelled,
    #[serde(rename = "OS_FILLED")]
    Filled,

}

impl std::fmt::Display for ApiOrderStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Unknown => write!(f, "OS_UNKNOWN"),
            Self::Open => write!(f, "OS_OPEN"),
            Self::PartialFill => write!(f, "OS_PARTIAL_FILL"),
            Self::Cancelled => write!(f, "OS_CANCELLED"),
            Self::Filled => write!(f, "OS_FILLED"),
        }
    }
}

impl Default for ApiOrderStatus {
    fn default() -> ApiOrderStatus {
        Self::Unknown
    }
}

