/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiGetMarketsResponseV2 {
    #[serde(rename = "markets", skip_serializing_if = "Option::is_none")]
    pub markets: Option<std::collections::HashMap<String, models::ApiMarketV2>>,
}

impl ApiGetMarketsResponseV2 {
    pub fn new() -> ApiGetMarketsResponseV2 {
        ApiGetMarketsResponseV2 {
            markets: None,
        }
    }
}

