/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiPostSubmitRequestEntry {
    #[serde(rename = "transaction", skip_serializing_if = "Option::is_none")]
    pub transaction: Option<Box<models::ApiTransactionMessage>>,
    #[serde(rename = "skipPreFlight", skip_serializing_if = "Option::is_none")]
    pub skip_pre_flight: Option<bool>,
}

impl ApiPostSubmitRequestEntry {
    pub fn new() -> ApiPostSubmitRequestEntry {
        ApiPostSubmitRequestEntry {
            transaction: None,
            skip_pre_flight: None,
        }
    }
}

