/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiUnsettledAccount {
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<String>,
    #[serde(rename = "baseToken", skip_serializing_if = "Option::is_none")]
    pub base_token: Option<Box<models::ApiUnsettledAccountToken>>,
    #[serde(rename = "quoteToken", skip_serializing_if = "Option::is_none")]
    pub quote_token: Option<Box<models::ApiUnsettledAccountToken>>,
}

impl ApiUnsettledAccount {
    pub fn new() -> ApiUnsettledAccount {
        ApiUnsettledAccount {
            account: None,
            base_token: None,
            quote_token: None,
        }
    }
}

