/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiGetPumpFunSwapsStreamResponse {
    #[serde(rename = "slot", skip_serializing_if = "Option::is_none")]
    pub slot: Option<String>,
    #[serde(rename = "txnHash", skip_serializing_if = "Option::is_none")]
    pub txn_hash: Option<String>,
    #[serde(rename = "mintAddress", skip_serializing_if = "Option::is_none")]
    pub mint_address: Option<String>,
    #[serde(rename = "userAddress", skip_serializing_if = "Option::is_none")]
    pub user_address: Option<String>,
    #[serde(rename = "userTokenAccountAddress", skip_serializing_if = "Option::is_none")]
    pub user_token_account_address: Option<String>,
    #[serde(rename = "bondingCurveAddress", skip_serializing_if = "Option::is_none")]
    pub bonding_curve_address: Option<String>,
    #[serde(rename = "tokenVaultAddress", skip_serializing_if = "Option::is_none")]
    pub token_vault_address: Option<String>,
    #[serde(rename = "solAmount", skip_serializing_if = "Option::is_none")]
    pub sol_amount: Option<String>,
    #[serde(rename = "tokenAmount", skip_serializing_if = "Option::is_none")]
    pub token_amount: Option<String>,
    #[serde(rename = "isBuy", skip_serializing_if = "Option::is_none")]
    pub is_buy: Option<bool>,
    #[serde(rename = "virtualSolReserves", skip_serializing_if = "Option::is_none")]
    pub virtual_sol_reserves: Option<String>,
    #[serde(rename = "virtualTokenReserves", skip_serializing_if = "Option::is_none")]
    pub virtual_token_reserves: Option<String>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
}

impl ApiGetPumpFunSwapsStreamResponse {
    pub fn new() -> ApiGetPumpFunSwapsStreamResponse {
        ApiGetPumpFunSwapsStreamResponse {
            slot: None,
            txn_hash: None,
            mint_address: None,
            user_address: None,
            user_token_account_address: None,
            bonding_curve_address: None,
            token_vault_address: None,
            sol_amount: None,
            token_amount: None,
            is_buy: None,
            virtual_sol_reserves: None,
            virtual_token_reserves: None,
            timestamp: None,
        }
    }
}

