/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiGetPumpFunQuotesResponse {
    #[serde(rename = "quoteType", skip_serializing_if = "Option::is_none")]
    pub quote_type: Option<String>,
    #[serde(rename = "inTokenAddress", skip_serializing_if = "Option::is_none")]
    pub in_token_address: Option<String>,
    #[serde(rename = "inAmount", skip_serializing_if = "Option::is_none")]
    pub in_amount: Option<f64>,
    #[serde(rename = "outTokenAddress", skip_serializing_if = "Option::is_none")]
    pub out_token_address: Option<String>,
    #[serde(rename = "outAmount", skip_serializing_if = "Option::is_none")]
    pub out_amount: Option<f64>,
}

impl ApiGetPumpFunQuotesResponse {
    pub fn new() -> ApiGetPumpFunQuotesResponse {
        ApiGetPumpFunQuotesResponse {
            quote_type: None,
            in_token_address: None,
            in_amount: None,
            out_token_address: None,
            out_amount: None,
        }
    }
}

