/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiUiTokenAmount {
    #[serde(rename = "uiAmount", skip_serializing_if = "Option::is_none")]
    pub ui_amount: Option<f64>,
    #[serde(rename = "decimals", skip_serializing_if = "Option::is_none")]
    pub decimals: Option<i64>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "uiAmountString", skip_serializing_if = "Option::is_none")]
    pub ui_amount_string: Option<String>,
}

impl ApiUiTokenAmount {
    pub fn new() -> ApiUiTokenAmount {
        ApiUiTokenAmount {
            ui_amount: None,
            decimals: None,
            amount: None,
            ui_amount_string: None,
        }
    }
}

