/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiGetBundleTipResponse {
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "percentile25", skip_serializing_if = "Option::is_none")]
    pub percentile25: Option<f64>,
    #[serde(rename = "percentile50", skip_serializing_if = "Option::is_none")]
    pub percentile50: Option<f64>,
    #[serde(rename = "percentile75", skip_serializing_if = "Option::is_none")]
    pub percentile75: Option<f64>,
    #[serde(rename = "percentile95", skip_serializing_if = "Option::is_none")]
    pub percentile95: Option<f64>,
    #[serde(rename = "percentile99", skip_serializing_if = "Option::is_none")]
    pub percentile99: Option<f64>,
    #[serde(rename = "emaPercentile50", skip_serializing_if = "Option::is_none")]
    pub ema_percentile50: Option<f64>,
}

impl ApiGetBundleTipResponse {
    pub fn new() -> ApiGetBundleTipResponse {
        ApiGetBundleTipResponse {
            timestamp: None,
            percentile25: None,
            percentile50: None,
            percentile75: None,
            percentile95: None,
            percentile99: None,
            ema_percentile50: None,
        }
    }
}

