/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiGetRaydiumPoolsResponse {
    #[serde(rename = "pools", skip_serializing_if = "Option::is_none")]
    pub pools: Option<Vec<models::ApiProjectPool>>,
}

impl ApiGetRaydiumPoolsResponse {
    pub fn new() -> ApiGetRaydiumPoolsResponse {
        ApiGetRaydiumPoolsResponse {
            pools: None,
        }
    }
}

