/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiPostCancelOrderRequestV2 {
    #[serde(rename = "orderID", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<String>,
    ///  Supported values : Bid, Ask
    #[serde(rename = "side")]
    pub side: String,
    #[serde(rename = "marketAddress")]
    pub market_address: String,
    #[serde(rename = "ownerAddress")]
    pub owner_address: String,
    #[serde(rename = "openOrdersAddress")]
    pub open_orders_address: String,
    #[serde(rename = "clientOrderID", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<String>,
    /// Optional: specifies total compute limit to be allocated for all instructions within the created tx
    #[serde(rename = "computeLimit", skip_serializing_if = "Option::is_none")]
    pub compute_limit: Option<i64>,
    /// Optional: specifies compute price in microlamports to be included as a part of instruction, known as priority fee
    #[serde(rename = "computePrice", skip_serializing_if = "Option::is_none")]
    pub compute_price: Option<String>,
    /// Optional: Specifies a tip amount that will be used to pay for front-running protection and/or bundle submission services. Minimum value is 1025
    #[serde(rename = "tip", skip_serializing_if = "Option::is_none")]
    pub tip: Option<String>,
}

impl ApiPostCancelOrderRequestV2 {
    pub fn new(side: String, market_address: String, owner_address: String, open_orders_address: String) -> ApiPostCancelOrderRequestV2 {
        ApiPostCancelOrderRequestV2 {
            order_id: None,
            side,
            market_address,
            owner_address,
            open_orders_address,
            client_order_id: None,
            compute_limit: None,
            compute_price: None,
            tip: None,
        }
    }
}

