/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiGetPumpFunNewTokensStreamResponse {
    #[serde(rename = "slot", skip_serializing_if = "Option::is_none")]
    pub slot: Option<String>,
    #[serde(rename = "txnHash", skip_serializing_if = "Option::is_none")]
    pub txn_hash: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    #[serde(rename = "mint", skip_serializing_if = "Option::is_none")]
    pub mint: Option<String>,
    #[serde(rename = "bondingCurve", skip_serializing_if = "Option::is_none")]
    pub bonding_curve: Option<String>,
    #[serde(rename = "creator", skip_serializing_if = "Option::is_none")]
    pub creator: Option<String>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
}

impl ApiGetPumpFunNewTokensStreamResponse {
    pub fn new() -> ApiGetPumpFunNewTokensStreamResponse {
        ApiGetPumpFunNewTokensStreamResponse {
            slot: None,
            txn_hash: None,
            name: None,
            symbol: None,
            uri: None,
            mint: None,
            bonding_curve: None,
            creator: None,
            timestamp: None,
        }
    }
}

