/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiPostCancelOrderResponseV2 {
    #[serde(rename = "transactions", skip_serializing_if = "Option::is_none")]
    pub transactions: Option<Vec<models::ApiTransactionMessage>>,
}

impl ApiPostCancelOrderResponseV2 {
    pub fn new() -> ApiPostCancelOrderResponseV2 {
        ApiPostCancelOrderResponseV2 {
            transactions: None,
        }
    }
}

