/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommonPriceImpactPercent {
    #[serde(rename = "percent", skip_serializing_if = "Option::is_none")]
    pub percent: Option<f64>,
    #[serde(rename = "infinity", skip_serializing_if = "Option::is_none")]
    pub infinity: Option<models::CommonInfinity>,
}

impl CommonPriceImpactPercent {
    pub fn new() -> CommonPriceImpactPercent {
        CommonPriceImpactPercent {
            percent: None,
            infinity: None,
        }
    }
}

