/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommonFee {
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f32>,
    #[serde(rename = "mint", skip_serializing_if = "Option::is_none")]
    pub mint: Option<String>,
    #[serde(rename = "percent", skip_serializing_if = "Option::is_none")]
    pub percent: Option<f32>,
}

impl CommonFee {
    pub fn new() -> CommonFee {
        CommonFee {
            amount: None,
            mint: None,
            percent: None,
        }
    }
}

