/*
 * Trader API
 *
 * Easy-to-use API for interacting with trader services on the Solana blockchain, powered by bloXroute Labs.
 *
 * The version of the OpenAPI document: 1.6
 * Contact: support@bloxroute.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CommonOrderType {
    #[serde(rename = "OT_MARKET")]
    Market,
    #[serde(rename = "OT_LIMIT")]
    Limit,
    #[serde(rename = "OT_IOC")]
    Ioc,
    #[serde(rename = "OT_POST")]
    Post,

}

impl std::fmt::Display for CommonOrderType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Market => write!(f, "OT_MARKET"),
            Self::Limit => write!(f, "OT_LIMIT"),
            Self::Ioc => write!(f, "OT_IOC"),
            Self::Post => write!(f, "OT_POST"),
        }
    }
}

impl Default for CommonOrderType {
    fn default() -> CommonOrderType {
        Self::Market
    }
}

